/**
 * ${PCU_USER}
 * ${PCU_SOURCE_FILE}
 * ${PCU_DATETIME}
 */

// BEGIN AUTOGENERATED

#include <assert.h>
#include <ctype.h>
#include <limits.h>
#include <math.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>


typedef long long int lli;


int gInt() {
    int i;
    scanf("%d", &i);
    return i;
}


lli gLong() {
    lli i;
    scanf("%lld", &i);
    return i;
}


double gDouble() {
    double i;
    scanf("%lf", &i);
    return i;
}


void init() {
}


void quit() {
    fclose(stdin);
    fclose(stdout);
    fclose(stderr);
    exit(0);
}


void body(int argc, char** argv);


int main(int argc, char** argv) {
    init();
    body(argc, argv);
    quit();
    return 0;
}

// END AUTOGENERATED


void body(int argc, char** argv) {
}
