/**
 * ${PCU_USER}
 * ${PCU_SOURCE_FILE}
 * ${PCU_DATETIME}
 */

// BEGIN AUTOGENERATED

#include <assert.h>
#include <ctype.h>
#include <limits.h>
#include <math.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#include <algorithm>
#include <array>
#include <bitset>
#include <chrono>
#include <complex>
#include <deque>
#include <forward_list>
#include <fstream>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <memory>
#include <numeric>
#include <queue>
#include <random>
#include <regex>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <tuple>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>


using namespace std;


typedef long long int lli;
typedef pair<int, int> pii;
typedef pair<int, lli> pil;
typedef pair<lli, int> pli;
typedef pair<lli, lli> pll;


int gInt() {
    int i;
    scanf("%d", &i);
    return i;
}


lli gLong() {
    lli i;
    scanf("%lld", &i);
    return i;
}


double gDouble() {
    double i;
    scanf("%lf", &i);
    return i;
}


void init() {
}


void quit() {
    fclose(stdin);
    fclose(stdout);
    fclose(stderr);
    exit(0);
}


void body(int argc, char** argv);


int main(int argc, char** argv) {
    init();
    body(argc, argv);
    quit();
    return 0;
}

// END AUTOGENERATED


void body(int argc, char** argv) {
}
