#!/usr/bin/env python3

"""
${PCU_USER}
${PCU_SOURCE_FILE}
${PCU_DATETIME}
"""

# BEGIN AUTOGENERATED

import array
import bisect
import cmath
import collections
import csv
import datetime
import functools
import heapq
import itertools
import math
import os
import re
import sys


def init():
    sys.stdin = open('${PCU_INPUT_FILE}', 'r')
    sys.stdout = open('${PCU_OUTPUT_FILE}', 'w')


def quit():
    sys.stdout.close()
    sys.stderr.close()


def main():
    init()
    body()
    quit()

# END AUTOGENERATED


def body():
    pass


if __name__ == '__main__':
    main()
