#!/usr/bin/env python2

"""
${PCU_USER}
${PCU_SOURCE_FILE}
${PCU_DATETIME}
"""

# BEGIN AUTOGENERATED

import array
import bisect
import cmath
import collections
import csv
import datetime
import functools
import heapq
import itertools
import math
import os
import re
import sys


def init():
    pass


def quit():
    sys.stdout.close()
    sys.stderr.close()


def main():
    init()
    body()
    quit()

# END AUTOGENERATED


def body():
    pass


if __name__ == '__main__':
    main()
